services:
  ghost1:
    build: .
    image: ubuntu-template:latest
    container_name: "${G1_NAME:-ghost-machine1}"
    restart: unless-stopped
    command: /usr/sbin/sshd -D
    ports:
      - "${G1_PORT:-2223}:22"
    cpuset: "${G1_CPUSET:-0}"
    volumes:
      - ${LXCFS_CPUINFO:-/dev/null}:/proc/cpuinfo:ro
      - ${LXCFS_MEMINFO:-/dev/null}:/proc/meminfo:ro
      - ${LXCFS_STAT:-/dev/null}:/proc/stat:ro
      - ${LXCFS_SWAPS:-/dev/null}:/proc/swaps:ro
      - ${LXCFS_UPTIME:-/dev/null}:/proc/uptime:ro
      - ./mounts/ubuntu1:/home/ubuntu
    deploy:
      resources:
        limits:
          cpus: "${G1_CPU:-1.0}"
          memory: "${G1_MEM:-8G}"
    networks:
      - sandbox_net

  ghost2:
    build: .
    image: ubuntu-template:latest
    container_name: "${G2_NAME:-ghost-machine2}"
    restart: unless-stopped
    command: /usr/sbin/sshd -D
    ports:
      - "${G2_PORT:-2224}:22"
    cpuset: "${G2_CPUSET:-1}"
    volumes:
      - ${LXCFS_CPUINFO:-/dev/null}:/proc/cpuinfo:ro
      - ${LXCFS_MEMINFO:-/dev/null}:/proc/meminfo:ro
      - ${LXCFS_STAT:-/dev/null}:/proc/stat:ro
      - ${LXCFS_SWAPS:-/dev/null}:/proc/swaps:ro
      - ${LXCFS_UPTIME:-/dev/null}:/proc/uptime:ro
      - ./mounts/ubuntu2:/home/ubuntu
    deploy:
      resources:
        limits:
          cpus: "${G2_CPU:-1.0}"
          memory: "${G2_MEM:-8G}"
    networks:
      - sandbox_net
    profiles:
      - dual

networks:
  sandbox_net:
    name: ghost_sandbox
    driver: bridge
